// ============================================================
// ChainResult.cs — Result data from a completed orb chain
// GDD: 01_combat_system.md v2.0 §2.2-2.3
// ============================================================

using System.Collections.Generic;
using UnityEngine;

namespace TOS.OrbBoard
{
    /// <summary>
    /// Immutable result of a player's chain connection.
    /// Consumed by the combat engine to trigger character skills.
    /// </summary>
    public class ChainResult
    {
        /// <summary>The orb type (element) of the chain.</summary>
        public Core.OrbType OrbType { get; }

        /// <summary>The combat element derived from the orb type.</summary>
        public Core.Element Element { get; }

        /// <summary>Ordered list of cell positions in the chain.</summary>
        public List<Vector2Int> Path { get; }

        /// <summary>Number of orbs connected.</summary>
        public int Length => Path.Count;

        /// <summary>Chain classification (Basic/Enhanced/Ultimate).</summary>
        public Core.ChainLength ChainLength { get; }

        /// <summary>AP cost consumed.</summary>
        public int APCost { get; }

        /// <summary>Divinity gauge generated by this chain.</summary>
        public float DivinityGenerated { get; }

        public ChainResult(Core.OrbType orbType, List<Vector2Int> path)
        {
            OrbType = orbType;
            Element = Core.AttributeChart.OrbToElement(orbType);
            Path = new List<Vector2Int>(path);
            ChainLength = OrbBoard.ClassifyChain(Length);
            APCost = OrbBoard.GetAPCost(ChainLength);
            DivinityGenerated = CalculateDivinityGain();
        }

        private float CalculateDivinityGain()
        {
            return ChainLength switch
            {
                Core.ChainLength.Basic    => Core.GameConstants.DIVINITY_PER_BASIC_CHAIN,
                Core.ChainLength.Enhanced => Core.GameConstants.DIVINITY_PER_ENHANCED_CHAIN,
                Core.ChainLength.Ultimate => Core.GameConstants.DIVINITY_PER_ULTIMATE_CHAIN,
                _ => 0f
            };
        }

        public override string ToString()
        {
            return $"Chain[{OrbType} x{Length} = {ChainLength}, {APCost}AP, +{DivinityGenerated}G]";
        }
    }

    /// <summary>
    /// Result of a cascade (skyfall) match — not player-initiated.
    /// Provides bonus combo and fixed damage, but does NOT trigger character skills.
    /// </summary>
    public class CascadeResult
    {
        public Core.OrbType OrbType { get; }
        public Core.Element Element { get; }
        public List<Vector2Int> MatchedPositions { get; }
        public int MatchCount => MatchedPositions.Count;

        public CascadeResult(Core.OrbType orbType, List<Vector2Int> positions)
        {
            OrbType = orbType;
            Element = Core.AttributeChart.OrbToElement(orbType);
            MatchedPositions = new List<Vector2Int>(positions);
        }

        public override string ToString()
        {
            return $"Cascade[{OrbType} x{MatchCount}]";
        }
    }
}
